/* ============================================================
   Interactive teaching widgets · Book 2 (khgeo/gis-fundamentals)
   Registered into window.EXTRA_SIMS; rendered by lesson-sims.js (lessons and slides).
   query-explorer · buffer-explorer · resolution-explorer · reclass-explorer · weights-explorer
   Generated by tools/slides/build_widgets.py — edit the template, not this file.
   ============================================================ */
(function () {
  "use strict";
  const KM = "០១២៣៤៥៦៧៨៩", kh = (n) => String(n).replace(/[0-9]/g, (d) => KM[d]);
  const khn = (n) => kh(Math.round(n).toLocaleString("en-US").replace(/,/g, " "));
  const BASE = (document.currentScript && document.currentScript.src) ? new URL("../data/", document.currentScript.src).href : "../assets/data/";
  const TERRAIN = __TERRAIN__;
  let geo = null;
  const loadGeo = async () => geo || (geo = await Promise.all(["lab-10/province.geojson", "lab-10/villages.geojson", "lab-10/health_centres.geojson"].map((p) => fetch(BASE + p).then((r) => r.json()))));
  const shell = (el, title, controls) => {
    el.innerHTML = `<div class="sim-title">${title}</div><div class="sim-controls">${controls}</div><div class="sim-body"><div class="sim-canvas-wrap w-map"></div></div><div class="sim-out"></div>`;
    return { map: el.querySelector(".w-map"), out: el.querySelector(".sim-out"), q: (s) => el.querySelector(s) };
  };
  const frame = (prov, W, H) => { const xs = [], ys = []; const walk = (c) => (typeof c[0] === "number" ? (xs.push(c[0]), ys.push(c[1])) : c.forEach(walk)); walk(prov.features[0].geometry.coordinates);
    const [x0, x1, y0, y1] = [Math.min(...xs), Math.max(...xs), Math.min(...ys), Math.max(...ys)], k = Math.cos(((y0 + y1) / 2) * Math.PI / 180);
    const s = Math.min(W / ((x1 - x0) * k), H / (y1 - y0)) * .96, ox = (W - (x1 - x0) * k * s) / 2, oy = (H - (y1 - y0) * s) / 2;
    const T = (lon, lat) => [ox + (lon - x0) * k * s, oy + (y1 - lat) * s]; T.pxkm = s / 111.32; return T; };
  const polyPath = (g, T) => { const polys = g.type === "MultiPolygon" ? g.coordinates : [g.coordinates]; return polys.map((p) => p.map((r) => "M" + r.map((c) => T(...c).map((v) => v.toFixed(1)).join(" ")).join(" L") + "Z").join(" ")).join(" "); };
  const km = (a, b) => { const k = Math.cos(12.2 * Math.PI / 180); return Math.hypot((a[0] - b[0]) * k, a[1] - b[1]) * 111.32; };
  window.EXTRA_SIMS = window.EXTRA_SIMS || {};

  /* ---------- attribute + distance query ---------- */
  window.EXTRA_SIMS["query-explorer"] = async (el) => {
    const { map, out, q } = shell(el, "សំណួរ៖ ភូមិធំ និងឆ្ងាយពីមណ្ឌលសុខភាព",
      `<label>"TOTPOP" &gt; <b class="qe-pv"></b> <input type="range" class="qe-p" min="0" max="5000" step="100" value="2000"></label>
       <label>ចម្ងាយ &gt; <b class="qe-dv"></b> គម <input type="range" class="qe-d" min="0" max="15" step="0.5" value="5"></label>
       <span class="sim-seg qe-o"><button type="button" data-o="and" class="on">AND</button><button type="button" data-o="or">OR</button></span>`);
    const [P, V, H] = await loadGeo(); const T = frame(P, 640, 400), hs = H.features.filter((h) => h.properties.in_prov).map((h) => h.geometry.coordinates);
    const vd = V.features.map((v) => ({ c: v.geometry.coordinates, pop: v.properties.TOTPOP, d: Math.min(...hs.map((h) => km(v.geometry.coordinates, h))) }));
    const draw = () => {
      const pmin = +q(".qe-p").value, dmin = +q(".qe-d").value, op = q(".qe-o .on").dataset.o; q(".qe-pv").textContent = khn(pmin); q(".qe-dv").textContent = kh(dmin);
      let svg = `<path d="${polyPath(P.features[0].geometry, T)}" fill="#f5f5f5" stroke="#90a4ae"/>`, n = 0, pop = 0;
      vd.forEach((v) => { const a = v.pop > pmin, b = v.d > dmin, s = op === "and" ? a && b : a || b; if (s) { n++; pop += v.pop; } const [x, y] = T(...v.c);
        svg += `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${s ? 4 : 2}" fill="${s ? "#e53935" : "#cfd8dc"}"/>`; });
      hs.forEach((h) => { const [x, y] = T(...h); svg += `<circle cx="${x}" cy="${y}" r="4" fill="#fff" stroke="#2e7d32" stroke-width="2"/>`; });
      map.innerHTML = `<svg viewBox="0 0 640 400" style="width:100%;height:auto;display:block">${svg}</svg>`;
      out.innerHTML = `<code>"TOTPOP" &gt; ${pmin} ${op.toUpperCase()} distance &gt; ${dmin} km</code> → <b>${kh(n)}</b> ភូមិ · ប្រជាជន ${khn(pop)} នាក់<br><span class="sim-hint">រង្វង់បៃតង = មណ្ឌលសុខភាព · ចម្ងាយត្រង់ (មិនមែនតាមផ្លូវ)</span>`;
    };
    el.querySelectorAll("input").forEach((i) => i.addEventListener("input", draw));
    el.querySelectorAll(".qe-o button").forEach((b) => (b.onclick = () => { el.querySelectorAll(".qe-o button").forEach((x) => x.classList.remove("on")); b.classList.add("on"); draw(); })); draw();
  };

  /* ---------- buffer coverage ---------- */
  window.EXTRA_SIMS["buffer-explorer"] = async (el) => {
    const { map, out, q } = shell(el, "បាហ្វ័រ និងប្រជាជនដែលទទួលបានសេវា",
      `<label>ចម្ងាយបាហ្វ័រ <b class="be-dv"></b> គម <input type="range" class="be-d" min="1" max="15" step="0.5" value="5"></label>
       <label><input type="checkbox" class="be-n" checked> រួមមណ្ឌលក្នុងខេត្តជិតខាង</label>`);
    const [P, V, H] = await loadGeo(); const T = frame(P, 640, 400);
    const draw = () => {
      const d = +q(".be-d").value, nb = q(".be-n").checked; q(".be-dv").textContent = kh(d);
      const hs = H.features.filter((h) => nb || h.properties.in_prov).map((h) => h.geometry.coordinates);
      let svg = `<defs><clipPath id="beclip"><path d="${polyPath(P.features[0].geometry, T)}"/></clipPath></defs><path d="${polyPath(P.features[0].geometry, T)}" fill="#f5f5f5" stroke="#90a4ae"/><g clip-path="url(#beclip)">`;
      hs.forEach((h) => { const [x, y] = T(...h); svg += `<circle cx="${x}" cy="${y}" r="${d * T.pxkm}" fill="#80cbc4" fill-opacity=".35"/>`; }); svg += "</g>";
      let pin = 0, ptot = 0;
      V.features.forEach((v) => { const c = v.geometry.coordinates, inside = hs.some((h) => km(c, h) <= d); ptot += v.properties.TOTPOP; if (inside) pin += v.properties.TOTPOP; const [x, y] = T(...c);
        svg += `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="2.2" fill="${inside ? "#00695c" : "#e53935"}"/>`; });
      hs.forEach((h) => { const [x, y] = T(...h); svg += `<circle cx="${x}" cy="${y}" r="3.5" fill="#fff" stroke="#004d40" stroke-width="1.5"/>`; });
      map.innerHTML = `<svg viewBox="0 0 640 400" style="width:100%;height:auto;display:block">${svg}</svg>`;
      out.innerHTML = `<b>${kh(Math.round(pin / ptot * 100))}%</b> នៃប្រជាជន (${khn(pin)} នាក់) រស់នៅក្នុង ${kh(d)} គម ពីមណ្ឌលសុខភាព · ${khn(ptot - pin)} នាក់នៅក្រៅ<br><span class="sim-hint">បិទ «ខេត្តជិតខាង» ដើម្បីមើលឥទ្ធិពលគែម</span>`;
    };
    el.querySelectorAll("input").forEach((i) => i.addEventListener("input", draw)); draw();
  };

  /* ---------- raster helpers ---------- */
  const Z = TERRAIN, N = Z.length, zmin = Math.min(...Z.flat()), zmax = Math.max(...Z.flat());
  const RAMP = ["#1a9641", "#a6d96a", "#ffffbf", "#fdae61", "#d7191c"];
  const hex = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
  const paint = (cv, grid, colour) => { const n = grid.length, ctx = cv.getContext("2d"); cv.width = n; cv.height = n; const im = ctx.createImageData(n, n);
    for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) { const c = colour(grid[i][j]), o = (i * n + j) * 4; im.data[o] = c[0]; im.data[o + 1] = c[1]; im.data[o + 2] = c[2]; im.data[o + 3] = 255; } ctx.putImageData(im, 0, 0); };
  const rampCol = (v, lo, hi, pal = RAMP) => hex(pal[Math.max(0, Math.min(pal.length - 1, Math.floor((v - lo) / (hi - lo + 1e-9) * pal.length)))]);
  const canv = (map, n) => { map.innerHTML = Array.from({ length: n }, () => `<canvas style="display:inline-block;vertical-align:top;width:${n === 1 ? 60 : 32}%;image-rendering:pixelated;margin:0 .6%"></canvas>`).join(""); return [...map.querySelectorAll("canvas")]; };
  const slope = (() => { const s = []; for (let i = 0; i < N; i++) { s.push([]); for (let j = 0; j < N; j++) { const dx = (Z[i][Math.min(N - 1, j + 1)] - Z[i][Math.max(0, j - 1)]) / 400, dy = (Z[Math.min(N - 1, i + 1)][j] - Z[Math.max(0, i - 1)][j]) / 400; s[i].push(Math.atan(Math.hypot(dx, dy)) * 180 / Math.PI); } } return s; })();

  window.EXTRA_SIMS["resolution-explorer"] = (el) => {
    const { map, out, q } = shell(el, "ទំហំក្រឡារ៉ាស្ទ័រ", `<label>ក្រឡា <b class="re-v"></b> <input type="range" class="re-s" min="1" max="12" value="1"></label>`);
    const [cv] = canv(map, 1);
    const draw = () => { const b = +q(".re-s").value, m = Math.floor(N / b); q(".re-v").textContent = khn(b * 200) + " ម";
      const g = []; for (let i = 0; i < m; i++) { g.push([]); for (let j = 0; j < m; j++) { let s = 0; for (let a = 0; a < b; a++) for (let c = 0; c < b; c++) s += Z[i * b + a][j * b + c]; g[i].push(s / (b * b)); } }
      paint(cv, g, (v) => rampCol(v, zmin, zmax)); const mx = Math.max(...g.flat());
      out.innerHTML = `ចំនួនក្រឡា៖ <b>${khn(m * m)}</b> · កម្ពស់ខ្ពស់បំផុតដែលឃើញ៖ <b>${kh(Math.round(mx))} ម</b> (ពិត ${kh(Math.round(zmax))} ម)<br><span class="sim-hint">ក្រឡាធំយកមធ្យម ដូច្នេះកំពូលភ្នំទាបជាងការពិត</span>`; };
    q(".re-s").addEventListener("input", draw); draw();
  };

  window.EXTRA_SIMS["reclass-explorer"] = (el) => {
    const { map, out, q } = shell(el, "Reclassify + Raster Calculator",
      `<label>កម្ពស់ &lt; <b class="rc-hv"></b> ម <input type="range" class="rc-h" min="20" max="350" step="10" value="150"></label>
       <label>ជម្រាល &lt; <b class="rc-sv"></b>° <input type="range" class="rc-s" min="1" max="15" step="0.5" value="5"></label>`);
    const [c1, c2, c3] = canv(map, 3);
    const draw = () => { const h = +q(".rc-h").value, s = +q(".rc-s").value; q(".rc-hv").textContent = kh(h); q(".rc-sv").textContent = kh(s);
      paint(c1, Z, (v) => (v < h ? [38, 166, 154] : [224, 224, 224])); paint(c2, slope, (v) => (v < s ? [66, 165, 245] : [224, 224, 224]));
      let n = 0; paint(c3, Z.map((r, i) => r.map((v, j) => { const ok = v < h && slope[i][j] < s; n += ok; return ok; })), (ok) => (ok ? [255, 112, 67] : [224, 224, 224]));
      out.innerHTML = `(<code>"dem" &lt; ${h}</code>) × (<code>"slope" &lt; ${s}</code>) → <b>${kh(Math.round(n / (N * N) * 100))}%</b> នៃតំបន់ (${khn(n * 4)} ហ.ត)<br><span class="sim-hint">ឆ្វេង៖ លក្ខខណ្ឌកម្ពស់ · កណ្ដាល៖ លក្ខខណ្ឌជម្រាល · ស្ដាំ៖ ទាំងពីរ (AND)</span>`; };
    el.querySelectorAll("input").forEach((i) => i.addEventListener("input", draw)); draw();
  };

  window.EXTRA_SIMS["weights-explorer"] = (el) => {
    const { map, out, q } = shell(el, "ទម្ងន់ MCDA",
      `<label>ជម្រាល <b class="we-av"></b> <input type="range" class="we-a" min="0" max="10" value="5"></label>
       <label>ជិតផ្លូវ <b class="we-bv"></b> <input type="range" class="we-b" min="0" max="10" value="3"></label>
       <label>ចម្ងាយទឹក <b class="we-cv"></b> <input type="range" class="we-c" min="0" max="10" value="2"></label>`);
    const [cv] = canv(map, 1);
    const f1 = slope.map((r) => r.map((v) => Math.max(0, Math.min(1, 1 - v / 10))));
    const f2 = Z.map((r, i) => r.map((v, j) => Math.max(0, Math.min(1, 1 - Math.abs(i - (20 + .3 * j)) * .2 / 6))));
    const f3 = Z.map((r, i) => r.map((v, j) => Math.max(0, Math.min(1, 1 - Math.abs(Math.hypot(j - 45, i - 45) * .2 - 4) / 6))));
    const draw = () => { let a = +q(".we-a").value, b = +q(".we-b").value, c = +q(".we-c").value; const s = a + b + c || 1;
      q(".we-av").textContent = kh((a / s).toFixed(2)); q(".we-bv").textContent = kh((b / s).toFixed(2)); q(".we-cv").textContent = kh((c / s).toFixed(2));
      let best = [0, 0, -1]; const g = f1.map((r, i) => r.map((v, j) => { const w = (a * v + b * f2[i][j] + c * f3[i][j]) / s; if (w > best[2]) best = [i, j, w]; return w; }));
      paint(cv, g, (v) => rampCol(v, 0, 1, ["#d73027", "#fc8d59", "#fee08b", "#91cf60", "#1a9850"]));
      out.innerHTML = `ទម្ងន់ត្រូវបានធ្វើឲ្យបូកគ្នា = ១ · ក្រឡាល្អបំផុតនៅជួរដេក ${kh(best[0])} ជួរឈរ ${kh(best[1])} (ពិន្ទុ ${kh(best[2].toFixed(2))})<br><span class="sim-hint">បៃតង = សមស្រប · ប្ដូរទម្ងន់ ហើយមើលថាតំបន់បៃតងរំកិលទៅណា</span>`; };
    el.querySelectorAll("input").forEach((i) => i.addEventListener("input", draw)); draw();
  };
})();
